[phases.setup]
aptPkgs = ["build-essential", "wget", "tar"]

[phases.install]
commands = [
  "wget https://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz",
  "tar -xzf ta-lib-0.4.0-src.tar.gz",
  "cd ta-lib && ./configure --prefix=/usr && make && make install"
]